#!/usr/bin/env python3
"""Render a secret-bearing NATS authorization include from a bcrypt-only roster."""

import argparse
import json
import os
import re
import tempfile
from pathlib import Path


NAME = re.compile(r"^[A-Za-z0-9_-]{1,48}$")
BCRYPT = re.compile(r"^\$2[aby]\$\d\d\$[./A-Za-z0-9]{53}$")


def quoted(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def validate_identity(identity: object, label: str) -> dict[str, str]:
    if not isinstance(identity, dict):
        raise ValueError(f"{label} must be an object")
    user = identity.get("user")
    bcrypt = identity.get("bcrypt")
    consumer = identity.get("consumer", user)
    if not isinstance(user, str) or not NAME.fullmatch(user):
        raise ValueError(f"{label}.user must match {NAME.pattern}")
    if not isinstance(consumer, str) or not NAME.fullmatch(consumer):
        raise ValueError(f"{label}.consumer must match {NAME.pattern}")
    if not isinstance(bcrypt, str) or not BCRYPT.fullmatch(bcrypt):
        raise ValueError(f"{label}.bcrypt must be a complete bcrypt hash")
    return {"user": user, "consumer": consumer, "bcrypt": bcrypt}


def render(roster: object) -> str:
    if not isinstance(roster, dict):
        raise ValueError("roster must be an object")
    admin = validate_identity(roster.get("admin"), "admin")
    members_raw = roster.get("members")
    if not isinstance(members_raw, list) or not members_raw:
        raise ValueError("members must be a non-empty array")
    members = [validate_identity(value, f"members[{index}]")
               for index, value in enumerate(members_raw)]
    users = [admin["user"], *(member["user"] for member in members)]
    consumers = [member["consumer"] for member in members]
    if len(set(users)) != len(users):
        raise ValueError("user names must be unique")
    if len(set(consumers)) != len(consumers):
        raise ValueError("consumer names must be unique")

    lines = [
        "# Generated by render_users.py. Contains password hashes; do not commit.",
        "authorization {",
        "  timeout: 2",
        "  users: [",
        "    {",
        f"      user: {quoted(admin['user'])}",
        f"      password: {quoted(admin['bcrypt'])}",
        '      permissions: { publish: ">", subscribe: ">" }',
        "    }",
    ]
    for member in members:
        user = quoted(member["user"])
        password = quoted(member["bcrypt"])
        consumer = member["consumer"]
        publish = ["chat.room.*", f"chat.dm.*.{member['user']}",
                   f"$JS.API.CONSUMER.MSG.NEXT.CAUSAL.{consumer}"]
        subscribe = ["chat.room.*", f"chat.dm.{member['user']}.*",
                     f"_INBOX.CAUSAL.{consumer}.>"]
        lines.extend([
            "    {",
            f"      user: {user}",
            f"      password: {password}",
            "      permissions: {",
            f"        publish: {json.dumps(publish)}",
            f"        subscribe: {json.dumps(subscribe)}",
            '        allow_responses: { max: 1, expires: "10s" }',
            "      }",
            "    }",
        ])
    lines.extend(["  ]", "}", ""])
    return "\n".join(lines)


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=path.name + ".", dir=path.parent)
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "w", encoding="utf-8") as output:
            output.write(content)
        os.replace(temporary, path)
    except BaseException:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("roster", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    roster = json.loads(args.roster.read_text(encoding="utf-8"))
    atomic_write(args.output, render(roster))
    print(f"rendered {args.output} with mode 0600")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
